<ips:template parameters="$lang, $type, $href=NULL, $class='', $attributes=array()" />
{{if $type === 'link'}}
	<a href="{$href}" class='ipsButton ipsButton--text {{if $class}}{$class}{{endif}}' {{if $attributes}}{{foreach $attributes as $key => $value}}{$key}="{$value}"{{endforeach}}{{endif}} role="button">{lang="$lang"}</a>
{{else}}
	<button type="{$type}" class="{{if $class}}{$class}{{endif}}" {{if $attributes}}{{foreach $attributes as $key => $value}}{$key}="{$value}"{{endforeach}}{{endif}} role="button">{lang="$lang"}</button>
{{endif}}