<ips:template parameters="$error" />
{{if $error !== NULL}}
	<div class='ipsMessage ipsMessage--error ipsMessage--form'>
		{lang="$error"}
	</div>
{{endif}}

<form method="post">
	<input type="hidden" name="login_submitted" value="1">
	<ul class='ipsForm ipsForm--vertical ipsForm--admin-upgrade'>
		<li class="ipsFieldRow">
			<label class="ipsFieldRow__label" for="auth">
				{lang="email_address"}
				<span class="ipsFieldRow__required">{lang="required"}</span>
			</label>
			<div class="ipsFieldRow__content">
				<input type="email" placeholder="{lang="email_address"}" name="auth" id="auth" {{if isset( \IPS\Request::i()->auth )}}value="{request="auth"}"{{endif}} style="width:100%">
			</div>
		</li>
		<li class="ipsFieldRow">
			<label class="ipsFieldRow__label" for="password">
				{lang="password"}
				<span class="ipsFieldRow__required">{lang="required"}</span>
			</label>
			<div class="ipsFieldRow__content">
				<input type="password" placeholder="{lang="password"}" name="password" id="password" {{if isset( \IPS\Request::i()->password )}}value="{request="password"}"{{endif}} style="width:100%">
			</div>
		</li>
		<li class='ipsSubmitRow'>
			<a href="{url="upgrader_login_help" ips="true"}" target="_blank" rel="noopener" class="ipsButton">{lang="help"}</a>
			<button type='submit' class='ipsButton ipsButton--primary'>{lang="login"}</button>
		</li>
	</ul>
</form>