<ips:template parameters="$url, $message" />
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{lang="redirecting"}</title>
		<link rel='stylesheet' href='../assets/css/reset.css' media='all'>
		<link rel='stylesheet' href='../assets/fontawesome/css/all.min.css' media='all'>
		<link rel='stylesheet' href='../assets/css/global.css' media='all'>
		<link rel='stylesheet' href='../assets/css/layout.css' media='all'>
		<link rel='stylesheet' href='../assets/css/messages.css' media='all'>
		<link rel='stylesheet' href='../assets/css/misc.css' media='all'>
		<link rel='stylesheet' href='../assets/css/forms.css' media='all'>
		<link rel='stylesheet' href='../assets/css/typography.css' media='all'>
		<link rel='stylesheet' href='../assets/css/buttons.css' media='all'>
		<link rel='stylesheet' href='../assets/css/installer.css' media='all'>
		<meta http-equiv="refresh" content="2; url={$url}" />
	</head>
	<body>
		<p class="ipsMessage ipsMessage--info ipsRedirectMessage">
			<strong>{lang="$message"}</strong><br />
			<br />
			{lang="redirecting_wait"}
		</p>
	</body>
</html>